### ISSUE TITLE
Unhandled rejection StatusCodeError: 504 - "Endpoint request timed out"

### ISSUE THREAD

**Issue by jameswilsterman** [request/request-promise#154] opened 2016-09-15 23:26 UTC
I've started seeing this error fairly reliably. It seems to happen when I send lots of requests in a row within a short time frame. Any thoughts?

Unhandled rejection StatusCodeError: 504 - {"message":"Endpoint request timed out"}
    at new StatusCodeError (/app/node_modules/request-promise/lib/errors.js:32:15)
    at Request.RP$callback [as _callback](/app/node_modules/request-promise/lib/rp.js:77:29)
    at Request.self.callback (/app/node_modules/request/request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1067:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:988:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by jameswilsterman** [comment] 2016-09-15 23:27
Also, to be clear, that's colon100colon not the emoji 💯

**Comment by analog-nico** [comment] 2016-09-15 23:40
Well, that is a very low level issue that may even be caused by the endpoint (server) and not your request itself. For some reason your request doesn't complete and you get a 504. This could be either because the server really does not respond because of the high workload and the request times out – see the [`timeout` option](https://github.com/request/request#requestoptions-callback) – or your node.js isn't configured well – see issue #133 in regard to the `pool` option.

Although you would rather get an [ECONNRESET](https://github.com/request/request-promise/issues/147) if the endpoint actually drops the connection, I wouldn't rule that out.

The best next step for you would be to activate [the debugging output](https://github.com/request/request-promise#debugging) to get a better picture about what is going on.

**Comment by jameswilsterman** [comment] 2016-09-16 08:08
Thank you for the response and advice. I am looking into the options above.

**Comment by analog-nico** [comment] 2017-03-23 06:53
I hope you found the cause @jameswilsterman . I am closing this issue now but don't hesitate to ping me again.

**Closed by analog-nico** 2017-03-23 06:53 UTC
