### ISSUE TITLE
Undefined header value yields an error that cannot be handled

### ISSUE THREAD

**Issue by Rush** [request/request-promise#66] opened 2015-10-13 11:45 UTC
I am using `request-promise` and I got a mysterious error:
```
Uncought exception Error: `value` required in setHeader("cookie", value).
at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:339:11)
at new ClientRequest (_http_client.js:80:14)
at Object.exports.request (http.js:31:10)
at Request.start (/opt/myapp/webapp/lib/app/frontend/node_modules/request/request.js:904:30)
at Request.end (/opt/myapp/webapp/lib/app/frontend/node_modules/request/request.js:1635:10)
at end (/opt/myapp/webapp/lib/app/frontend/node_modules/request/request.js:676:14)
at Immediate._onImmediate (/opt/myapp/webapp/lib/app/frontend/node_modules/request/request.js:690:7)
at processImmediate [as _immediateCallback] (timers.js:374:17)
```

seems that if you do a:
```js
rp({
  uri: 'http://localhost:60000/some/route',
  method: 'GET',
  resolveWithFullResponse: true,
  headers: {
    cookie: undefined
  }
});
```
you will get an exception that cannot be handled

**Comment by analog-nico** [comment] 2015-10-13 12:59
Hi @Rush, the error is used to reject the Bluebird promise. Since you don't handle the error Bluebird is printing the error message.

What you need to do it to add a catch handler:
``` js
rp({
  uri: 'http://localhost:60000/some/route',
  method: 'GET',
  resolveWithFullResponse: true,
  headers: {
    cookie: undefined
  }
})
  .catch(function (err) {
    // Handle your error here.
  });
```

Does this help?

**Comment by Rush** [comment] 2015-10-13 13:02
Nope, it's not bluebird. Bluebird would print `Unhandled rejection`. This error is simply not passed to the Promise, it's not rejecting the promise and simply crashing my app. I can catch it with `uncaughtException` event only.

**Comment by analog-nico** [comment] 2015-10-13 13:13
Oh, I see. I just ran the code in my environment and didn't even get an error - the request succeeded. I use node 0.10.40, request-promise 1.0.0, and request 2.65.0. Which versions do you use?

**Comment by Rush** [comment] 2015-10-13 13:14
Node 4.1.2. I didn't get any errors before 0.12 -> 4.1 upgrade.

**Comment by analog-nico** [comment] 2015-10-13 13:23
Sorry, I still don't get an error with node 4.1.2.

My test code prints "done":
``` js
var rp = require('request-promise');

rp({
    uri: 'http://localhost:3000/some/route',
    method: 'GET',
    resolveWithFullResponse: true,
    headers: {
        cookie: undefined
    }
})
    .then(function () {
        console.log('done');
    });
```

Can you check if you provided the correct code snippet?

**Comment by analog-nico** [comment] 2015-10-20 10:49
Where you able to fix the issue? If not, please help me to reproduce the error.

**Comment by analog-nico** [comment] 2015-11-11 08:38
Hi @Rush I am closing this issue now. If you need some help feel free to reopen this issue.

**Closed by analog-nico** 2015-11-11 08:38 UTC
