### ISSUE TITLE
Warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by teckays** [request/request-promise#119] opened 2016-05-24 14:31 UTC
I have this warning `Warning: a promise was created in a handler but was not returned from it` at: `request-promise/lib/rp.js:117:28`

**Comment by analog-nico** [comment] 2016-05-24 18:56
Can you provide a code snippet to reproduce the warning?

**Comment by BarrieP** [comment] 2016-05-27 18:40
Hi, I seem to be getting the same... not sure if I've been chasing it half the day, or if I also had the same issue myself - but I've learnt more about promises! :)

This is the first promise that's called, and is generating the same error :

`    function getNewAuthToken() {
        var options = {
            url: AUTH_PATH.replace('{IdentityDomain}', konfig.identityDomain),
            method: 'GET',
            resolveWithFullResponse: true,
            headers: {}
        };
        options.headers[X_STORAGE_USER] = X_STORAGE_USER_TEMPLATE.replace('{IdentityDomain}', konfig.identityDomain).replace('{user}', konfig.user);
        options.headers[X_STORAGE_PASS] = X_STORAGE_PASS_TEMPLATE.replace('{pwd}', konfig.pwd);

        var newExpiryTime = new Date().getTime() + expirationPeriod;
        return request(options)
            .then(function(res) {
                expiryTime = newExpiryTime;
                return res.headers[X_AUTH_TOKEN];
            })
            .catch(function(err) {
                console.log('Error getting new token for oracle storage cloud');
                console.log(helpers.prettyJSON(err));
                return Promise.reject(err);
            })
    }`

**Comment by BarrieP** [comment] 2016-05-28 20:09
I'm getting the same, with the following code.
If I uncomment the "Promise.resolve(testToken)" line, then the problem goes away.

I can't for the life of me think why I'm getting it for this GET, and not the numerous others I'm doing... ( well, I do have one other instance of this error to track down ).  Sorry I can't pin it down any further... ( and also sorry if it's my defect, I'm new to promises... )

```
    function getNewAuthToken() {
        var options = {
            url: AUTH_PATH.replace('{IdentityDomain}', konfig.identityDomain),
            method: 'GET',
            resolveWithFullResponse: true,
            headers: {}
        };
        options.headers[X_STORAGE_USER] = X_STORAGE_USER_TEMPLATE.replace('{IdentityDomain}', konfig.identityDomain).replace('{user}', konfig.user);
        options.headers[X_STORAGE_PASS] = X_STORAGE_PASS_TEMPLATE.replace('{pwd}', konfig.pwd);

        var newExpiryTime = new Date().getTime() + expirationPeriod;
        //return Promise.resolve(testToken());
        return request(options)
            .then(function(res) {
                expiryTime = newExpiryTime;
                //authToken = res.headers[X_AUTH_TOKEN];
                //return authToken;
                return res.headers[X_AUTH_TOKEN];
            })
            .catch(function(err) {
                console.log('Error getting new token for oracle storage cloud');
                console.log(helpers.prettyJSON(err));
                return Promise.reject(err);
            })
    }
```

**Comment by BarrieP** [comment] 2016-05-31 17:32
The other instances of the error were intermittant, and have now stopped...  Is posting about an issue the opposite of demo-ing to a manager...

**Comment by analog-nico** [comment] 2016-05-31 20:45
Haha, awesome @BarrieP ! Does it mean you are all good now?

Btw, you may replace `return Promise.reject(err);` with just `throw err;` inside your catch block.

**Comment by analog-nico** [comment] 2016-05-31 20:50
@teckays Do you still observe your reported error?

Judging from the error message it is related to how you did the request call. See: https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it

**Comment by BarrieP** [comment] 2016-05-31 21:24
It all seems fine today, which does mean I probably wasted most of Saturday... The code snippet above was 100% reproducible in Sat... but today, nothing...
All I can think that's changed is I've "turned it off and on again" ( both linux VM and host Win machine ).

**Comment by analog-nico** [comment] 2016-07-09 20:47
I think it is safe to close this issue now. Feel free to ask follow up questions if you want.

**Closed by analog-nico** 2016-07-09 20:47 UTC

**Comment by analog-nico** [comment] 2016-07-19 20:21
Hey @teckays and @BarrieP ! The same warning was reported in #139 and we found the cause. Just fyi.
