### ISSUE TITLE
Support statusCode 304 - Not Modified

### ISSUE THREAD

**Issue by alobaidizt** [request/request-promise#156] opened 2016-10-12 00:51 UTC
Responses returning with statusCode 304 are causing the promise be rejected with the following error.

![Error snapshot](http://i.imgur.com/Cltpy2T.png)

**Comment by analog-nico** [comment] 2016-10-12 01:32
Yes, that works as intended. But anyways:

- Can I help you with ways to handle those responses?
- Or do you ask for ETag-based resource caching to be implemented in `request-promise`?

**Comment by alobaidizt** [comment] 2016-10-12 03:07
@analog-nico yeah, I'm using `request-promise` to test for caching implementation based on `ETag` and `IF-None-Match`.

I implemented a workaround, but it's more of a hack than a real solution:
```
  try
    responseTwo = yield request(options)
  catch err
    expect(err.statusCode).to.equal(304)
```

Do you have any recommendation on how to handle it otherwise?

**Comment by analog-nico** [comment] 2016-10-12 03:31
If you want 304 responses to be fulfilled instead of rejected then you may use the [`simple` option](https://github.com/request/request-promise#rejected-promises-and-the-simple-option) set to `false`. This will resolve all responses with any status code so you may need to throw an error for the other status codes.

If you use `simple = true` then `request-promise` throws any non 2xx response with a `StatusCodeError`. You may check for this error type in `catch` or use `simple = false` and use this error type for throwing non-304 responses yourself.

If you decide to use `simple = false` you can use the `.defaults(...)` function to change the defaults:

``` js
let rp = require('request-promise')
let rpNonSimple = rp.defaults({ simple: false })

yield rpNonSimple(...) // You don't have to set the simple option again
```

Does this help?

**Comment by alobaidizt** [comment] 2016-10-12 04:36
Thanks @analog-nico! Yeah, that definitely helps. I've set `simple` to `false` but `request-promise` is returning statusCode of `200` now.. Didn't expect that. Any speculations to why this happened?

Thanks for the help!

**Comment by analog-nico** [comment] 2016-10-12 04:39
The `simple` option only changes what response fulfills or rejects the promise. It doesn't interfere with the actual request/response. I bet it is related to your test case. Maybe you are sending an outdated ETag?

**Comment by alobaidizt** [comment] 2016-10-12 04:45
Possibly, will investigate further tomorrow morning. 👍

**Comment by alobaidizt** [comment] 2016-10-12 23:23
Could you add a test for `ETag` support? It should expect back a `statusCode` of `304`

**Comment by analog-nico** [comment] 2016-11-10 23:55
Hi @alobaidizt all involved libraries have extensive test coverage. In the case of ETags:
- `request-promise` is tested to forward all options to `request` - which is relevant for the headers you use
- `request` is tested to apply the options including headers to the request dispatched using the core node.js functionality
- That the server responds as expected is out of scope of course
- `request` is tested to return the status code received from the server the request was sent to
- `request-promise` is fully tested to resolve/reject the promise with the correct response data including the status code

Do you see the need for extra test cases somewhere? Please let me know.

**Comment by alobaidizt** [comment] 2016-11-12 22:29
No, thanks @analog-nico for the clarification!

**Closed** 2016-11-12 22:29 UTC

**Comment by analog-nico** [comment] 2016-11-12 22:31
Alright, have a nice weekend!

**Comment by alobaidizt** [comment] 2016-11-12 22:35
Thanks! You too!

**Comment by igordeoliveirasa** [comment] 2017-05-09 12:50
Anyway, how to get the response at error scope of try/catch ? I'd like to return the response.

**Comment by igordeoliveirasa** [comment] 2017-05-09 12:57
When I use simple, response comes empty string.

**Comment by analog-nico** [comment] 2017-05-09 16:35
Hi @igordeoliveirasa , when you catch the 304 `StatusCodeError` you can access the full response via [`err.response`](https://github.com/request/promise-core/blob/master/lib/errors.js#L29).

The fact that you get an empty string for the response body is actually the purpose of 304 responses. When you are sending an ETag to your server you say: “I have this resource in my cache. Please tell me if I can use it or send me the correct resource.” When the server is responding with a 304 it says: “Yes, your cached resource is the right one. Use the one in your cache. So no need for me to send you the resource.” Thus the response body is empty.

**Comment by henricazottes** [comment] 2017-10-11 10:10
Hi @analog-nico ,

I still have a problems handling the 304 error... As @igordeoliveirasa  I want to get the body of the cached response if I get a 304. You said the response was in err.reponse but I end up with an IncomingMessage within I can't find what I'm looking for. Would you have any advice ?

Thanks

**Comment by RobGraham** [comment] 2017-10-11 15:18
@henricazottes as long as you're using `resolveWithFullResponse: true` option in your requests, the 304 responses will be sent to the `catch` method of your promise chain. This is how i handle them:

```
.catch(error => {
        const status = error.statusCode;

        if (status === 304) {
                .......do stuff
        }
}
```

**Comment by henricazottes** [comment] 2017-10-11 15:31
I agree with you, but here is my situation:
```
let result;
try {
    result = await rp.get(options);
} catch (e) {
    result = e.response;
}
```
If **200 OK** then result is what I was waiting for, but in case of **304** result is `undefined`. My question is do I have to store/cache manually the answer when it is **200 OK** to get it in case of **304** or is there a way to directly retrieve the previously body, like reading the cache ?

Hope my question is clearer :)

**Comment by RobGraham** [comment] 2017-10-11 15:43
Yes. I think we're getting off topic here but you would need to cache any successful 200 response and in the case of a 304 being returned, your code should resort to cache.

**Comment by henricazottes** [comment] 2017-10-11 16:06
Ok, I though request was high level enough to do it for us. Thanks for your help 👍
